import { chromium, expect } from "@playwright/test";
import { PDFDocument } from "pdf-lib";
import { mkdtemp, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createCore } from "../apps/core/src/server";

const data = await mkdtemp(join(tmpdir(), "aireader-ink-smoke-"));
await mkdir(".local/screenshots", { recursive: true });
const core = createCore(data, resolve("dist/web"));
const pdf = await PDFDocument.create();
pdf.addPage([400, 300]).drawText("First page", { x: 30, y: 240 });
pdf.addPage([400, 300]).drawText("Second page", { x: 30, y: 240 });
const book = await core.library.import(Buffer.from(await pdf.save()), "Ink acceptance.pdf");
await core.library.waitForBook(book.id);
await new Promise<void>((done) => core.server.listen(0, "127.0.0.1", done));
const address = core.server.address();
if (!address || typeof address === "string") throw new Error("Missing port");
const origin = `http://127.0.0.1:${address.port}`;
const browser = await chromium.launch({ channel: "msedge", headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(origin);
  await page.getByRole("button", { name: /Ink acceptance/ }).click();
  await expect(page.locator("#page-2")).toHaveAttribute("data-render-ready", "true");
  const first = (await page.locator("#page-1").boundingBox())!;
  const second = (await page.locator("#page-2").boundingBox())!;
  await page.getByRole("button", { name: "画笔（P）" }).click();
  await expect(page.getByRole("button", { name: "画笔（P）" })).toHaveAttribute("aria-pressed", "true");
  await page.mouse.move(first.x + 100, first.y + first.height - 70);
  await page.mouse.down();
  await page.mouse.move(second.x + 100, second.y + 70, { steps: 30 });
  await page.mouse.up();
  const endpoint = `${origin}/api/books/${book.id}/workspace`;
  await expect.poll(async () => (await (await page.request.get(endpoint)).json()).objects.length).toBe(1);
  const stored = await (await page.request.get(endpoint)).json();
  expect(stored.objects[0].segments.map((segment: { surface: { kind: string; page?: number } }) =>
    segment.surface.kind === "pdf" ? segment.surface.page : "board")).toEqual([1, "board", 2]);
  await page.screenshot({ path: ".local/screenshots/ink-cross-page.png" });
  await page.getByRole("button", { name: "画笔（P）" }).click();
  const settings = page.getByRole("dialog", { name: "画笔设置" });
  await expect(settings).toBeVisible();
  await settings.getByRole("button", { name: "粗细 8" }).click();
  await settings.getByRole("button", { name: "颜色 #d35e45" }).click();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "指针（V）" })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "画笔（P）" }).click();
  const reading = (await page.locator(".reading").boundingBox())!;
  await page.mouse.move(reading.x + 160, reading.y + 250);
  await page.mouse.down();
  await page.mouse.move(reading.x + 220, reading.y + 270, { steps: 8 });
  await page.mouse.up();
  await expect.poll(async () => (await (await page.request.get(endpoint)).json()).objects.length).toBe(2);
  const two = await (await page.request.get(endpoint)).json();
  expect(two.objects[1]).toMatchObject({ brush: "pen", width: 8, color: "#d35e45" });
  expect(two.objects[1].segments[0].surface.kind).toBe("board");
  await page.getByRole("button", { name: "整笔橡皮（E）" }).click();
  await page.mouse.click(second.x + 100, second.y + 70);
  await expect.poll(async () => (await (await page.request.get(endpoint)).json()).objects.length).toBe(1);
  await page.getByRole("button", { name: "撤销工作区修改" }).click();
  await expect.poll(async () => (await (await page.request.get(endpoint)).json()).objects.length).toBe(2);
  await page.reload();
  await page.getByRole("button", { name: /Ink acceptance/ }).click();
  await expect(page.getByRole("button", { name: "指针（V）" })).toHaveAttribute("aria-pressed", "true");
  expect((await (await page.request.get(endpoint)).json()).objects).toHaveLength(2);
  await page.getByRole("button", { name: "画笔（P）" }).click();
  await page.getByRole("button", { name: "画笔（P）" }).click();
  await expect(page.getByRole("dialog", { name: "画笔设置" }).getByRole("button", { name: "粗细 8" })).toHaveAttribute("aria-pressed", "true");
  expect(errors).toEqual([]);
  console.log("Cross-page ink, board ink, brush settings, whole-stroke eraser, undo and restart passed.");
} finally {
  await browser.close();
  core.close();
}
