import { chromium, expect } from "@playwright/test";
import { PDFDocument } from "pdf-lib";
import { mkdtemp, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createCore } from "../apps/core/src/server";

const data = await mkdtemp(join(tmpdir(), "aireader-objects-smoke-"));
await mkdir(".local/screenshots", { recursive: true });
const core = createCore(data, resolve("dist/web"));
const pdf = await PDFDocument.create();
pdf.addPage([400, 320]).drawText("Object page one", { x: 30, y: 260 });
pdf.addPage([400, 320]).drawText("Object page two", { x: 30, y: 260 });
const book = await core.library.import(Buffer.from(await pdf.save()), "Object acceptance.pdf");
await core.library.waitForBook(book.id);
await new Promise<void>((done) => core.server.listen(0, "127.0.0.1", done));
const address = core.server.address();
if (!address || typeof address === "string") throw new Error("Missing port");
const origin = `http://127.0.0.1:${address.port}`;
const browser = await chromium.launch({ channel: "msedge", headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(origin);
  await page.getByRole("button", { name: /Object acceptance/ }).click();
  await expect(page.locator("#page-1")).toHaveAttribute("data-render-ready", "true");
  const first = (await page.locator("#page-1").boundingBox())!;
  const workspace = async () => (await (await page.request.get(`${origin}/api/books/${book.id}/workspace`)).json());
  await page.getByRole("button", { name: "添加文本或卡片" }).click();
  await page.getByRole("menuitem", { name: "文本" }).click();
  await page.mouse.click(first.x + 80, first.y + 100);
  await expect(page.getByLabel("编辑画布文本")).toBeVisible();
  await page.getByLabel("编辑画布文本").fill("中文想法：比较两个概念");
  await page.getByLabel("编辑画布文本").press("Tab");
  await expect.poll(async () => (await workspace()).objects.length).toBe(1);
  const text = (await workspace()).objects[0];
  expect(text).toMatchObject({ kind: "text", text: "中文想法：比较两个概念", surface: { kind: "pdf", page: 1 } });
  await page.getByRole("button", { name: "添加形状" }).click();
  await page.getByRole("menuitem", { name: "矩形" }).click();
  await page.mouse.move(first.x + 50, first.y + 180);
  await page.mouse.down();
  await page.mouse.move(first.x + 180, first.y + 250, { steps: 8 });
  await page.mouse.up();
  await expect.poll(async () => (await workspace()).objects.length).toBe(2);
  expect((await workspace()).objects[1]).toMatchObject({ kind: "shape", shape: "rectangle", surface: { kind: "pdf", page: 1 } });
  await page.getByRole("button", { name: "添加文本或卡片" }).click();
  await page.getByRole("menuitem", { name: "个人笔记卡片" }).click();
  await page.mouse.click(first.x + first.width + 100, first.y + 190);
  await expect.poll(async () => (await workspace()).cards.length).toBe(1);
  await page.getByRole("button", { name: "关系连线" }).click();
  await page.locator(`[data-object-id="${text.id}"]`).click();
  await page.locator(".workspace-card").first().click();
  await expect.poll(async () => (await workspace()).links.length).toBe(1);
  expect((await workspace()).links[0]).toMatchObject({ from: text.id });
  await page.getByRole("button", { name: "指针（V）" }).click();
  const before = (await workspace()).objects[0];
  const textBox = (await page.locator(`[data-object-id="${text.id}"]`).boundingBox())!;
  await page.mouse.move(textBox.x + 20, textBox.y + 15);
  await page.mouse.down();
  await page.mouse.move(textBox.x + 45, textBox.y + 35, { steps: 5 });
  await page.mouse.up();
  await expect.poll(async () => (await workspace()).objects[0].x).not.toBe(before.x);
  await page.keyboard.press("l");
  await expect(page.getByRole("button", { name: "套索（L）" })).toHaveAttribute("aria-pressed", "true");
  const moved = (await page.locator(`[data-object-id="${text.id}"]`).boundingBox())!;
  await page.mouse.move(moved.x - 20, moved.y - 20);
  await page.mouse.down();
  for (const [x, y] of [[moved.x + moved.width + 20, moved.y - 20],
    [moved.x + moved.width + 20, moved.y + moved.height + 20],
    [moved.x - 20, moved.y + moved.height + 20], [moved.x - 20, moved.y - 20]])
    await page.mouse.move(x, y, { steps: 5 });
  await page.mouse.up();
  await expect(page.getByRole("toolbar", { name: "对象操作" })).toBeVisible();
  await page.screenshot({ path: ".local/screenshots/objects-lasso.png" });
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "指针（V）" })).toHaveAttribute("aria-pressed", "true");
  await page.reload();
  await page.getByRole("button", { name: /Object acceptance/ }).click();
  expect((await workspace()).objects).toHaveLength(2);
  expect((await workspace()).links).toHaveLength(1);
  expect(errors).toEqual([]);
  console.log("Text, shape, card link, lasso, object move, and restart passed.");
} finally {
  await browser.close();
  await new Promise<void>((done) => core.server.close(() => done()));
  core.library.close();
}
